name: PrivescCheck Update & Build


on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write

env:
  NAME_BATGADGET: PrivescCheck
  BATGADGET_EXTENSION: ps1

jobs:

  build-scripts:
    name: Build PrivescCheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0
      - name: Build PrivescCheck script
        shell: pwsh
        run: |
          . ./build/Build.ps1
          Invoke-Build -Name "PrivescCheck" -NoNewSeed
          ls
          ls ./release

      - name: package stuff
        run: |
            ls
            env
            cp ./release/${{ env.NAME_BATGADGET }}.${{ env.BATGADGET_EXTENSION }} .
            zip ${{ env.NAME_BATGADGET }}.zip ${{ env.NAME_BATGADGET }}.${{ env.BATGADGET_EXTENSION }}
            ls


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.NAME_BATGADGET }}.zip
          asset_name: ${{ env.NAME_BATGADGET }}.zip
          asset_content_type: application/zip
